// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0X-L1G4xJi95-A-5O0jMGo40BaZDUnPY',
    appId: '1:9833790450:web:91062bd33b1c01cffb096b',
    messagingSenderId: '9833790450',
    projectId: 'mantenimiento-3fc49',
    authDomain: 'mantenimiento-3fc49.firebaseapp.com',
    storageBucket: 'mantenimiento-3fc49.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1tQJazhAPw8Uj29NCqknRX1iIknbfMOg',
    appId: '1:9833790450:android:b186d7312541515cfb096b',
    messagingSenderId: '9833790450',
    projectId: 'mantenimiento-3fc49',
    storageBucket: 'mantenimiento-3fc49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_fpBjUJZMkB_-nHWpjTdMFkDgyX8SUQ8',
    appId: '1:9833790450:ios:9f4dfa39f2ffcd7afb096b',
    messagingSenderId: '9833790450',
    projectId: 'mantenimiento-3fc49',
    storageBucket: 'mantenimiento-3fc49.firebasestorage.app',
    iosClientId: '9833790450-9pba7e6vfukk24nm3pi5panuf173fkd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mantenimientoPanoramic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_fpBjUJZMkB_-nHWpjTdMFkDgyX8SUQ8',
    appId: '1:9833790450:ios:9f4dfa39f2ffcd7afb096b',
    messagingSenderId: '9833790450',
    projectId: 'mantenimiento-3fc49',
    storageBucket: 'mantenimiento-3fc49.firebasestorage.app',
    iosClientId: '9833790450-9pba7e6vfukk24nm3pi5panuf173fkd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mantenimientoPanoramic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0X-L1G4xJi95-A-5O0jMGo40BaZDUnPY',
    appId: '1:9833790450:web:b57c63d7079f2724fb096b',
    messagingSenderId: '9833790450',
    projectId: 'mantenimiento-3fc49',
    authDomain: 'mantenimiento-3fc49.firebaseapp.com',
    storageBucket: 'mantenimiento-3fc49.firebasestorage.app',
  );
}
